---
abstract: 'Test all modules which depend on your module'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Copy::Recursive: 0
  File::Find: 0
  Module::Build: 0
  Module::Build::Tiny: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DependentModules
no_index:
  directory:
    - corpus
recommends:
  Parallel::ForkManager: v0.7.6
requires:
  CPAN: 0
  CPAN::Shell: 0
  Capture::Tiny: 0
  Cwd: 0
  Exporter: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  File::chdir: 0
  IO::Handle::Util: 0
  IPC::Run3: 0
  Log::Dispatch: 0
  MetaCPAN::API: 0
  Test::Builder: 0
  Try::Tiny: 0
  autodie: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-DependentModules
  homepage: http://metacpan.org/release/Test-DependentModules
  repository: git://git.urth.org/Test-DependentModules.git
version: 0.18
x_authority: cpan:DROLSKY
x_contributors:
  - 'Graham Knop <haarg@haarg.org>'
  - 'Jesse Luehrs <doy@tozt.net>'
