---
abstract: 'Test all modules which depend on your module'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DependentModules
recommends:
  Parallel::ForkManager: 0.7.6
requires:
  CPAN: 1.9402
  CPANDB: 0.12
  Cwd: 0
  Exporter: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  File::chdir: 0
  IO::Handle::Util: 0
  IPC::Run3: 0
  Log::Dispatch: 0
  Scope::Guard: 0
  Test::More: 0
  autodie: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-DependentModules
  repository: git://git.urth.org/Test-DependentModules.git
version: 0.12
